### ISSUE TITLE
Q: which is new disabilitymeasures website?

### ISSUE THREAD

**Issue by ghost** [mjmaenner/disabilitymeasures#2]
hello, which one is the new website? The first will jump to second.

1. https://mjmaenner.github.io/disabilitymeasures

2. http://disabilitymeasures.org

**Comment by mjmaenner** [comment]
disabilitymeasures.org has always been the domain we recommend people use.  We moved this to GH pages from a wordpress site, making this the "new" site.  

After 5 years, it is no longer "new" -- I've updated the project description. Thanks!
